/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Features;

/**
 *
 * @author Rane
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuOptions = new javax.swing.JPopupMenu();
        Home = new javax.swing.JMenuItem();
        ItemManagement = new javax.swing.JMenuItem();
        BorrowingRecords = new javax.swing.JMenuItem();
        ReportsLogs = new javax.swing.JMenuItem();
        Profile = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jOptions = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Home.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Home_icon.png"))); // NOI18N
        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        MenuOptions.add(Home);

        ItemManagement.setFont(new java.awt.Font("Imprint MT Shadow", 0, 14)); // NOI18N
        ItemManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/ItemManagement_icon.png"))); // NOI18N
        ItemManagement.setText("Item Management");
        ItemManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemManagementActionPerformed(evt);
            }
        });
        MenuOptions.add(ItemManagement);

        BorrowingRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BorrowingRecords_icon.png"))); // NOI18N
        BorrowingRecords.setText("Borrowing Records");
        BorrowingRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowingRecordsActionPerformed(evt);
            }
        });
        MenuOptions.add(BorrowingRecords);

        ReportsLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/ReportsLogs_icon.png"))); // NOI18N
        ReportsLogs.setText("Reports and Logs");
        ReportsLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsLogsActionPerformed(evt);
            }
        });
        MenuOptions.add(ReportsLogs);

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Profile_icon.png"))); // NOI18N
        Profile.setText("Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        MenuOptions.add(Profile);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jOptions.setBackground(new java.awt.Color(51, 51, 51));
        jOptions.setFont(new java.awt.Font("Imprint MT Shadow", 1, 12)); // NOI18N
        jOptions.setForeground(new java.awt.Color(255, 255, 255));
        jOptions.setText("MENU");
        jOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOptionsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PROFILE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jOptions)
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jOptions)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 390, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void ItemManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemManagementActionPerformed
        ItemManagement item = new ItemManagement();
        item.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemManagementActionPerformed

    private void BorrowingRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowingRecordsActionPerformed
        BorrowingRecords record = new BorrowingRecords();
        record.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BorrowingRecordsActionPerformed

    private void ReportsLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsLogsActionPerformed
        ReportsLogs report = new ReportsLogs();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportsLogsActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void jOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOptionsActionPerformed
        MenuOptions.show(jOptions, 0, jOptions.getHeight());
    }//GEN-LAST:event_jOptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JMenuItem BorrowingRecords;
    protected javax.swing.JMenuItem Home;
    protected javax.swing.JMenuItem ItemManagement;
    private javax.swing.JPopupMenu MenuOptions;
    protected javax.swing.JMenuItem Profile;
    protected javax.swing.JMenuItem ReportsLogs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jOptions;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
